name: Execute Serial Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Compiling
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make install
    - name: LS
      run: ls
    - name: Run py-script
      run: |
        cd tests
        python run_all_tests.py
